[package]
name = "packedit"
version = "1.1.1"
edition = "2024"
description = "Raw packet edit crate on pure rust"
license = "MIT"

[features]
default = []
advanced-arp = []
advanced = [
    "advanced-arp"
]
